package com.zhangteng.xim.db.dao;

import com.zhangteng.xim.db.bean.LocalUser;
import com.zhangteng.xim.db.bean.NewFriend;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final UserDao userDao;

    private final DaoConfig newFriendDaoConfig;
    private final NewFriendDao newFriendDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);
        userDao = new UserDao(userDaoConfig, this);
        registerDao(LocalUser.class, userDao);

        newFriendDaoConfig = daoConfigMap.get(NewFriendDao.class).clone();
        newFriendDaoConfig.initIdentityScope(type);
        newFriendDao = new NewFriendDao(newFriendDaoConfig, this);
        registerDao(NewFriend.class, newFriendDao);
    }

    public void clear() {
        userDaoConfig.clearIdentityScope();
        newFriendDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public NewFriendDao getNewFriendDao() {
        return newFriendDao;
    }
}
